sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t conradnewton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true conradnewton/react-test npm test

after_success:
  - docker build -t conradnewton/multi-client-10-14 ./client
  - docker build -t conradnewton/multi-nginx-10-14 ./nginx
  - docker build -t conradnewton/multi-server-10-14 ./server
  - docker build -t conradnewton/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  #- docker push conradnewton/multi-client-10-14
  #- docker push conradnewton/multi-nginx-10-14
  #- docker push conradnewton/multi-server-10-14
  #- docker push conradnewton/multi-worker-10-14

#deploy:
  #provider: elasticbeanstalk
  #region: 'us-east-1'
  #app: 'multi-docker'
  #env: 'MultiDocker-env'
  #bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  #bucket_path: 'docker-multi'
  #on:
    #branch: master
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET_KEY
